---
abstract: 'Perl extension for accessing the Logic or Logic16 devices made by Saleae Logic.'
author:
  - 'Vikas Kumar <vikas@selectiveintellect.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
  File::ShareDir::Install: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.132661'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-SaleaeLogic
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Zip: 0
  LWP::Simple: 0
version: 0.02
